courses/urls.py
from django.urls import path
from . import views

app_name='courses'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('courses_list/', views.courses_list, name='courses_list'),
    path('<slug:course_slug>/', views.course_view, name='course_view'),
    path('<slug:course_slug>/<slug:process_slug>/', views.process_view, name='process_view'),
    path('<slug:course_slug>/<slug:process_slug>/<slug:action_slug>/', views.action_view, name='action_view'),
    
    
]

twi/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('courses/', include('courses.urls',  namespace='courses')),
    path('client/', include('client_interface.urls', namespace='client_interface')),
    path('account/', include('account.urls', namespace='account')),

    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

courses/models.py
from django.db import models
from django.shortcuts import reverse
from django.template.defaultfilters import slugify
from autoslug import AutoSlugField
import datetime, pytils
from account.models import Account


class Course(models.Model):
    title = models.CharField(max_length=100)
    date_added = models.DateTimeField(auto_now_add=True)
    description = models.CharField(max_length=250)
    cover = models.ImageField(upload_to = 'media/courses/covers/static/', null=True)
    slug = AutoSlugField(populate_from='title', unique=True, db_index=True)
    owner = models.ForeignKey(Account, on_delete=models.CASCADE, null=True)

    def get_absolute_url(self):
        return f'/courses/{self.title}/'

    def __str__(self):
        return self.title


class Process(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=255)
    cover = models.ImageField(upload_to = 'media/courses/covers/static/', null=True)
    slug = AutoSlugField(populate_from='title', unique=True, db_index=True)

    def get_absolute_url(self):
        return reverse('process', kwargs={'process_slug': self.slug})

    def __str__(self):
        return self.title

class Action(models.Model):
    process = models.ForeignKey(Process, on_delete=models.CASCADE, default=1)
    title = models.CharField(max_length=100)
    description = models.TextField()
    cover = models.ImageField(upload_to = 'media/courses/covers/static/', null=True)
    slug = AutoSlugField(populate_from='title', unique=True, db_index=True)
    

    def get_absolute_url(self):
        return reverse('action', kwargs={'action_slug': self.slug})

    def __str__(self):
        return self.title


class Step(models.Model):
    action = models.ForeignKey(Action, related_name='step', on_delete=models.CASCADE)
    step_title = models.CharField(max_length=100)
    key_moment = models.CharField(max_length=250)
    key_moment_reason = models.CharField(max_length=250, null=True)
    slug = AutoSlugField(populate_from='step_title', unique=True, db_index=True)

    def get_absolute_url(self):
        return reverse('step', kwargs={'step_slug': self.slug})

    def __str__(self):
        return self.title


class ActionPhoto(models.Model):
    photo = models.ImageField(upload_to = 'media/courses/actions/photos/static/', null=True)
    action = models.ForeignKey(Action, related_name='photos', on_delete=models.CASCADE, default=1)

class ActionVideo(models.Model):
    video = models.FileField(upload_to='media/courses/actions/videos/', null=True)
    action = models.ForeignKey(Action, related_name='video', on_delete=models.CASCADE, default=1)

courses/views.py
from django.conf import settings
from django.shortcuts import render, redirect, get_object_or_404
from .models import Course, Action, Step, ActionPhoto, ActionVideo, Process



"""main page"""
def index(request):
    return render(request, 'courses/index.html')


"""showing views"""
def courses_list(request):
    courses = Course.objects.all()
    return render(request, 'courses/courses_list.html', {'courses': courses})

def course_view(request, course_slug):
    course = get_object_or_404(Course, slug=course_slug)
    processes = course.process_set.all()
    return render(request, 'courses/course.html', {'course': course, 'processes': processes})

def process_view(request, course_slug, process_slug):
    process = Process.objects.get(slug=process_slug)
    actions = process.action_set.all()
    return render (request, 'courses/process.html', {'process': process,'actions': actions})

def action_view(request, course_slug, process_slug, action_slug):
    action = Action.objects.get(slug=action_slug)
    steps = Step.objects.filter(action=action)
    photos = action.photos.all()
    video = action.video.all()
    context = {'action': action, 'steps': steps, 'photos': photos, 'video': video}
    return render(request, 'courses/action.html', context)

courses/templates/courses/action.html
{% extends 'courses/base.html' %}

<head>
    <meta charset="UTF-8">
    {% block title %}
    <title> {{action.process.course.title}}</title>
   {% endblock %}
</head>

<body>
    {% block content %}
    <h4 class="text-center"> {{course.title}}</h4>
    <div class="text-center">
      {% for step in steps %}
        <div class="d-flex gap-2 w-100 justify-content-between">
          <div>
            <h5>{{step.title}}</h5>
            <p>{{step.description}}</p>
          </div>
        </div>
      {% endfor %}
      <div>
        <p> {{action.main_text}}</p>
      </div>
      <div>
        {% if photos %}
        {% for photo in photos %}
        <img src="{{photo.photo.url}}" class="img-thumbnails">
        {% endfor %}
        {% endif %}
        {% if video %}
            <video src="{{video.video.url}}" type="video/mp4" controls autoplay width='50%' height='40%'>
            </video>
            {% endif %}
      </div>
    </div>
    {% endblock %}
  </body>

courses/templates/courses/base.html
{% load static %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<!DOCTYPE html>
<html lang="ru">

    <head> 
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, intial-scale=1, shrink-to-fit=no">
        {% block title %}{%endblock%}
    </head>

<body>
    <nav class="navbar-light navbar-expand-lg bg-light rounded" style="background-color: #CCCCCC" aria-label="Twelfth navbar example">
        <div class="container-fluid">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample10" aria-controls="navbarsExample10" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
  
          <div class="collapse navbar-collapse justify-content-md-center" id="navbarsExample10">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" aria-current="page" href="{% url 'courses:index' %}">TWI обучение</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'client_interface:index' %}">Войти в аккаунт</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown" aria-expanded="false"> Меню</a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="#">Философия проекта</a></li>
                  <li><a class="dropdown-item" href="#">Стать партнером</a></li>
                  <li><a class="dropdown-item" href="#">Что то еще</a></li>
                </ul>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      <div class="text-center">
        {% block content %}{% endblock %}
      </div>
</body>
    

courses/templates/courses/course.html
{% extends 'courses/base.html' %}

<head>
    <meta charset="UTF-8">
    {% block title %}
    <title> {{process.course.title}}</title>
   {% endblock %}
</head>

<body>
  {% block content %}
  <h4 class="text-center"> {{course.title}}</h4>
  <div class="list-group w-auto">
    {% for process in processes %}
    <a href="/courses/{{course.slug}}/{{process.slug}}/" class="list-group-item list-group-item-action d-flex gap-3 py-3" aria-current="true">
      <div class="d-flex gap-2 w-100 justify-content-between">
        <div>
         <h6 class="mb-0">{{process.title}}</h6>
        </div>
        <div>
          <p>{{process.description}}</p>
        </div>
      </div>
    </a>
    {% endfor %}
  </div>
  {% endblock %}
</body>

courses/templates/courses/courses_list.html
{% extends 'courses/base.html' %}


<head>
   <meta charset="UTF-8">
   {% block title %}
    <title> Доступные курсы </title>
   {% endblock %}
</head>

<body>
   {% block content %}
   <div class="container-fluid px-4 py-5" id="featured-3">
      <h2 class="pb-2 border-bottom">Доступные курсы</h2>
      
      <div class="row g-4 py-5 row-cols-1 row-cols-lg-3">
         {% for course in courses %} 
        <div class="feature col" style="background-color: #f1f1f0ec">
          <h2>{{course.title}}</h2>
          <p>{{course.description | linebreaks }}</p>
          <p class="text-secondary"> {{course.date_added}}</p>
          <a href="{% url 'courses:course_view' course.slug %}" class="icon-link d-inline-flex align-items-center">
            Перейти к курсу
            <svg class="bi" width="1em" height="1em"><use xlink:href="#chevron-right"/></svg>
          </a>
        </div>
        <br>
        {% endfor %}
      </div>
    </div>
    
  {% endblock %}
</body>

courses/templates/courses/index.html
{% extends 'courses/base.html' %}

{% block content %}
  <h5> test text </h5>
  <p> по ссылке Войти в аккаунт пока переход на клиентский интерфейс, так как нет аутентификации.
    Потом будет переход на страницу логина и после нее уже к клиентскому интерфейсу управления курсами и ботами
  </p>
  <p>В выпадающем меню сейчас все ссылки никуда не ведут
    Предполагаю, что там будут страницы с информацией и формой обратной связи (для потенциальных клиентов)
    Туда (и вообще в навбар), можно добавить любое количество ссылок на что угодно
  </p>
{% endblock content %}

courses/templates/courses/process.html
{% extends 'courses/base.html' %}

<head>
    <meta charset="UTF-8">
    {% block title %}
    <title> {{process.course.title}}</title>
   {% endblock %}
</head>

<body>
    {% block content %}
    <h4 class="text-center"> {{course.title}}</h4>
    <div class="list-group w-auto">
      {% for action in actions %}
      <a href="/courses/{{course.slug}}/{{process.slug}}/{{action.slug}}" class="list-group-item list-group-item-action d-flex gap-3 py-3" aria-current="true">{{step.title}}</a>
        <div class="d-flex gap-2 w-100 justify-content-between">
    </div>
    {% endfor %}
    {% endblock %}
  </body>