account/urls.py
from django.urls import path
from account.views import (
            login_view,
            logout_view,
            account,
            registration,
        )


app_name = 'account'

urlpatterns  = [
    path('register/',registration, name="register" ),
    path('logout/',logout_view, name="logout" ),
    path('login/',login_view, name="login" ),
    path('profile/',account, name="account" ),
]

client_interface/urls.py
from django.urls import path
from . import views

app_name = 'client_interface'

urlpatterns = [
    #CREATION
    path('', views.index, name='index'),
    path('course_creation/', views.course_creation, name='course_creation'),
    path('<slug:course_slug>/course_added/', views.course_added, name='course_added'),
    path('<slug:course_slug>/process_creation/', views.process_creation, name='process_creation'),
    path('<slug:course_slug>/<slug:process_slug>/process_added/', views.process_added, name='process_added'),
    path('<slug:course_slug>/<slug:process_slug>/action_creation/', views.action_creation, name='action_creation'),
    path('<slug:course_slug>/<slug:process_slug>/<slug:action_slug>/action_added/', views.action_added, name='action_added'),
    #EDITING
    path('courses/<slug:course_slug>/edit/', views.course_editing, name='course_editing'),
    path('courses/<slug:course_slug>/<slug:process_slug>/edit/', views.process_editing, name='process_editing'),
    path('courses/<slug:course_slug>/<slug:process_slug>/<slug:action_slug>/edit/', views.action_editing, name='action_editing'),
    #DELETING
    path('courses/<slug:course_slug>/deletion/', views.course_deleting, name='course_deleting'),
    path('courses/<slug:course_slug>/<slug:process_slug>/deletion/', views.process_deleting, name='process_deleting'),
    path('courses/<slug:course_slug>/<slug:process_slug>/<slug:action_slug>/deletion/', views.action_deleting, name='action_deleting'),
    #SHOWING
    path('courses/<slug:course_slug>/', views.course_showing, name='course_showing'),
    path('courses/<slug:course_slug>/<slug:process_slug>/', views.process_showing, name='process_showing'),
    path('courses/<slug:course_slug>/<slug:process_slug>/<slug:action_slug>/', views.action_showing, name='action_showing'),
   

]

twi/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('courses/', include('courses.urls',  namespace='courses')),
    path('client/', include('client_interface.urls', namespace='client_interface')),
    path('account/', include('account.urls', namespace='account')),

    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

client_interface/models.py
from django.db import models

# Create your models here.

#TODO add basic auth!

client_interface/forms.py
from django import forms
from django.forms.models import inlineformset_factory, BaseInlineFormSet
from courses.models import Course, Action, Step, Process, ActionPhoto, ActionVideo


class CourseCreationForm(forms.ModelForm):
    title = forms.CharField(max_length=100, widget=forms.TextInput)
    description = forms.CharField(max_length=255, widget=forms.Textarea)
    cover = forms.ImageField(widget=forms.FileInput, required=False)
    class Meta:
        model = Course
        fields = ['title', 'description', 'cover']

class ProcessCreationForm(forms.ModelForm):
    title = forms.CharField(max_length=100, widget=forms.TextInput)  
    description = forms.CharField(max_length=255, widget=forms.Textarea)
    cover = forms.ImageField(widget=forms.FileInput, required=False)
    class Meta:
        model = Process
        fields = ['title', 'description', 'cover']  

class ActionCreationForm(forms.ModelForm):
    process = forms.CharField(max_length=128) 
    title = forms.CharField(max_length=128, widget=forms.TextInput)
    cover = forms.ImageField(widget=forms.FileInput, required=False)
    description = forms.CharField(max_length=500, widget=forms.Textarea)
    photos = forms.ImageField(widget=forms.FileInput(attrs={'multiple': 'multiple'}), required=False)
    video = forms.FileField(widget=forms.FileInput, required=False)
    class Meta:
        model = Action
        fields = ['title', 'description', 'cover']

class StepCreationForm(forms.ModelForm):
    action = forms.CharField(max_length=128, required=False)
    step_title = forms.CharField(max_length=128, widget=forms.TextInput)
    key_moment = forms.CharField(max_length=256, widget=forms.Textarea)
    key_moment_reason = forms.CharField(max_length=1000, widget=forms.Textarea)
    class Meta:
        model = Step
        fields = ['step_title', 'key_moment', 'key_moment_reason']

client_interface/views.py
from django.conf import settings
from django import forms
from django.shortcuts import render, redirect
from django.core.files.storage import FileSystemStorage
from django.core.files.base import ContentFile
from django.contrib.auth.decorators import login_required
from django.template.defaultfilters import slugify
from .forms import CourseCreationForm, ActionCreationForm, ProcessCreationForm, StepCreationForm
from courses.models import Course, Action, Step, ActionPhoto, ActionVideo, Process

"""main client page"""
@login_required
def index(request):
    courses = Course.objects.filter(owner=request.user)
    context = {'courses': courses}
    return render(request, 'client_interface/index.html', context)

"""course creation views"""
@login_required
def course_creation(request):
    courses = Course.objects.filter(owner=request.user)
    if request.method == 'POST':
        form = CourseCreationForm(request.POST, request.FILES)
        if form.is_valid():
            cd = form.cleaned_data
            course = Course.objects.create(title=cd['title'],
            description=cd['description'],
            cover=cd['cover'],
            slug=slugify(cd['title']),
            owner=request.user)
            return redirect('client_interface:course_added', course.slug)
        raise ValidationError(_(form.errors))
    form = CourseCreationForm()
    return render(request, 'client_interface/course_creation.html', {'courses': courses, 'form': form})

@login_required
def course_added(request, course_slug):
    courses = Course.objects.filter(owner=request.user)
    course = Course.objects.get(slug=course_slug)
    return render(request, 'client_interface/course_added.html', {'courses': courses, 'course': course})

@login_required
def process_creation(request, course_slug):
    courses = Course.objects.filter(owner=request.user)
    course = Course.objects.get(slug=course_slug)
    if request.method == 'POST':
        form = ProcessCreationForm(request.POST, request.FILES)
        if form.is_valid():
            cd = form.cleaned_data
            process = Process.objects.create(course=course,
                                        title=cd['title'],
                                        description=cd['description'],
                                        cover=cd['cover'])
            return redirect('client_interface:process_added', course_slug, process.slug)
        raise print(form.errors)
    form = ProcessCreationForm()
    context = {'courses': courses, 'form': form}
    return render(request, 'client_interface/process_creation.html', context)

@login_required
def process_added(request, course_slug, process_slug):
    courses = Course.objects.filter(owner=request.user)
    process = Process.objects.get(slug=process_slug)
    context = {'courses': courses, 'process': process}
    return render(request, 'client_interface/process_added.html', context)

def process_choices_execute(course_slug, process_slug):
    course = Course.objects.get(slug=course_slug)
    process = Process.objects.get(slug=process_slug)
    queryset = course.process_set.all()
    processes = []
    keys = []
    for process in queryset:
        processes.append(process.title)
        keys.append(process.title)
    process_choices = [(key, process) for key, process in zip(keys, processes)]
    return process_choices

@login_required
def action_creation(request, course_slug, process_slug):
    courses = Course.objects.filter(owner=request.user)
    course = Course.objects.get(slug=course_slug)
    process = Process.objects.get(slug=process_slug)
    if request.method == 'POST':
        action_form = ActionCreationForm(request.POST, request.FILES)
        step_form = StepCreationForm(request.POST)
        if action_form.is_valid() and step_form.is_valid():
            acd = action_form.cleaned_data
            scd = step_form.cleaned_data
            process = Process.objects.get(title=acd['process'])
            action = Action.objects.create(process=process,
                                title=acd['title'],
                                description=acd['description'],
                                cover=acd['cover'] or None,
                                slug=slugify(acd['title']))
            action.save()
            step = Step.objects.create(action=action, step_title=scd['step_title'],
                                    key_moment=scd['key_moment'], 
                                key_moment_reason=scd['key_moment_reason'],
                                slug=slugify(scd['step_title']))
            for f in request.FILES.getlist('photos'):
                data = f.read()
                photo = ActionPhoto(action=action)
                photo.photo.save(f.name, ContentFile(data))
                photo.save()
            if acd['video']:
                video = ActionVideo(action=action, video=request.FILES['video'])
                video.save()
            return redirect('client_interface:action_added', course_slug, process.slug, action.slug)
        else:
            #test errors print
            print(action_form.errors, step_form.errors)
    else:
        process_choices = process_choices_execute(course_slug, process_slug)
        choice_field = forms.ChoiceField(widget=forms.Select(),
                                     choices=process_choices)
        action_form = ActionCreationForm(initial={})
        action_form.fields['process'] = choice_field
        action_choices = action_choices_execute(course_slug, process_slug)
        choice_field = forms.ChoiceField(widget=forms.Select(),
                                     choices=action_choices,required=False)
        step_form = StepCreationForm(initial={})
        step_form.fields['action'] = choice_field
        context = { 'courses': courses, 'course': course, 'process': process,
                             'action_form': action_form, 'step_form': step_form } 
        return render(request, 'client_interface/action_creation.html', { 'courses': courses, 'course': course, 'process': process,
                             'action_form': action_form, 'step_form': step_form })
    
@login_required
def action_added(request, course_slug, process_slug, action_slug):
    courses = Course.objects.filter(owner=request.user)
    process = Process.objects.get(slug=process_slug)
    action = Action.objects.get(slug=action_slug)
    context = {'courses': courses, 'process': process, 'action': action}
    return render(request, 'client_interface/action_added.html', context)


def action_choices_execute(course_slug, process_slug):
    course = Course.objects.get(slug=course_slug)
    process = Process.objects.get(slug=process_slug)
    queryset = process.action_set.all()
    actions = []
    keys = []
    for action in queryset:
        actions.append(action.title)
        keys.append(action.title)
    action_choices = [(key, action) for key, action in zip(keys, actions)]
    return action_choices

"""showing view """

@login_required
def course_showing(request, course_slug):
    courses = Course.objects.filter(owner=request.user)
    course = Course.objects.get(slug=course_slug)
    processes = course.process_set.all()
    context = {'courses': courses, 'course': course, 'processes': processes}
    return render (request, 'client_interface/course_showing.html', context)

@login_required
def process_showing(request, course_slug, process_slug):
    courses = Course.objects.filter(owner=request.user)
    process = Process.objects.get(slug=process_slug)
    actions = process.action_set.all()
    context = {'courses': courses, 'process': process, 'actions': actions}
    return render(request, 'client_interface/process_showing.html', context)

@login_required
def action_showing(request, course_slug, process_slug, action_slug):
    courses = Course.objects.filter(owner=request.user)
    course = Course.objects.get(slug=course_slug)
    process = Process.objects.get(slug=process_slug)
    action = Action.objects.get(slug=action_slug)
    steps = Step.objects.filter(action=action)
    photos = action.photos.all()
    try:
        video = ActionVideo.objects.get(action=action)
        context = {'courses': courses, 'course': course, 'process': process, 'action': action, 'steps': steps, 'photos': photos, 'video': video}
    except:
        context = {'courses': courses, 'course': course, 'process': process, 'action': action, 'steps': steps, 'photos': photos}
    return render(request, 'client_interface/action_showing.html', context)

"""editing"""
@login_required
def course_editing(request, course_slug):
    courses = Course.objects.filter(owner=request.user)
    course = Course.objects.filter(slug=course_slug).first()
    if request.method == 'POST':
        form = CourseCreationForm(instance=course, data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            return redirect('client_interface:course_showing', course.slug)
    form = CourseCreationForm(instance=course)
    return render(request, 'client_interface/course_edit.html', {'courses': courses, 'course': course, 
                'form': form})

@login_required
def process_editing(request, course_slug, process_slug):
    courses = Course.objects.filter(owner=request.user)
    process = Process.objects.filter(slug=process_slug).first()
    if request.method == 'POST':
        form = ProcessCreationForm(instance=process,data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            return redirect('client_interface:course_showing', course_slug)
    form = ProcessCreationForm(instance=process)
    context = {'courses': courses, 'process': process, 'form': form}
    return render(request, 'client_interface/process_edit.html', context)
    
@login_required
# need to change(add steps) 
def action_editing(request, course_slug, process_slug, action_slug):
    courses = Course.objects.filter(owner=request.user)

client_interface/templates/client_interface/action_added.html
{% extends 'client_interface/base.html' %}

<head>
    {% block title %}
    <title>
        Курс {{action.process.course.title}}
    </title>
    {% endblock %}
</head>

<body>
    {% block content %}
    <div class="px-4 py-5 my-5 text-center">
        <h1 class="display-5 fw-bold">Этап {{action.title}} для процесса {{action.process.title}} успешно создан</h1>
        <div class="col-lg-6 mx-auto">
          <p class="lead mb-4">Любой нужный текст</p>
          <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
            <a href="{% url 'client_interface:action_creation' action.process.course.slug  action.process.slug %}" class="btn btn-secondary btn-lg px-4 gap-3">Создать еще один этап</a>
            
            <a href="{% url 'client_interface:process_showing' action.process.course.slug action.process.slug %}" class="btn btn-secondary btn-lg px-4 gap-3">Перейти на страницу процесса </a>
          </div>
        </div>
      </div>
    {% endblock %}
</body>

client_interface/templates/client_interface/action_showing.html
{% extends 'client_interface/base.html' %}
{% load static %}

<head>
    {% block title %}
    <title>
        {{action.process.course.title}}
    </title>
    {% endblock %}
</head>

<body>
    {% block content %}
    <br>
    <br>
    <br>
    <h1 class="display-5 fw-bold text-center"> Процесс {{action.process.title}}</h1>
    <div class="text-end">
        <a href="{% url 'client_interface:process_editing' action.process.course.slug action.process.slug %}" class="btn btn-outline-primary">Редактировать процесс</a>
    </div>
    <div class="px-3 py-5 my-4 text-center">
        {% if video %}
            <video src="{{video.video.url}}" type="video/mp4" controls autoplay width='50%' height='40%'>
            </video>
            {% endif %}
    </div>
    <div class="px-3 py-5 my-4 text-center">
        {% if photos %}
        {% for photo in photos %}
        <img src="{{photo.photo.url}}" class="img-thumbnails">
        {% endfor %}
        {% endif %}
    </div>
    <div class="px-3 py-5 my-4 text-center">
        <p> {{action.main_text}}</p>
    </div>
    <table class="table">
        <col style="width:15%">
        <col style="width:15%">
        <col style="width:20%">
        <col style="width:40%">
        <col style="width:15%">
        <thead>
            <tr>
              <th scope="col">Этап"</th>
              <th scope="col">Ключевой момент</th>
              <th scope="col">Причина выделения ключевого момента</th>
              <th scope="col">Действия</th>
            </tr>
        </thead>
        <tbody>
                {% for step in steps %}
            <tr>
                <td scope="row" style="background-color: #CCCCCC">{{step.title | linebreaks}}</td> 
                <td scope="row">{{step.title}}</td>
                <td scope="row" style="background-color: #CCCCCC">{{step.key_moment}}</td>
                <td scope="row" style="background-color: #CCCCCC">{{step.key_moment_reason}}</td>
                <td scope="row" style="background-color: #CCCCCC" class="text-end">
                    <br>
                </td>
                {% endfor %}
            </tr>
    </table>
  {% endblock %}   
</body>

client_interface/templates/client_interface/base.html
{% load static %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, intial-scale=1, shrink-to-fit=no">
        {% block title %}{%endblock%}
</head>

<body>
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark" style="background-color: #a0a0a0f3">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'client_interface:index' %}">TWI</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">О проекте</a>
          </li>
          <li class="nav-item">
            <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown" aria-expanded="false">Боты</a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="#">{ название бота }</a></li>
              <li><a class="dropdown-item" href="#">{ название бота }</a></li>
              <li><a class="dropdown-item" href="#">{ название бота }</a></li>
            </ul>
          </li>
          <li class="nav-item">
            <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown" aria-expanded="false">Курсы</a>
            <ul class="dropdown-menu">
              {% if courses %}
              {% for course in courses %}
              <li><a class="dropdown-item" href="{% url 'client_interface:course_showing' course.slug %}">{{course.title}}</a></li>
              {% endfor %}
              <li><a class="dropdown-item" href="{% url 'client_interface:course_creation' %}">Новый курс</a></li>
              {% else %}
              <li><a class="dropdown-item" href="{% url 'client_interface:course_creation' %}">Новый курс</a></li>
            </ul>
          </li>
          {% endif %}
          </li>
        </ul>
        <li class="d-flex text-end">
          <a class="nav-link active" style="color:rgba(255, 255, 255, 0.89)" href="{% url 'account:logout' %}">Выйти</a>
        </li>
      </div>
    </div>
  </nav>
  <div class="text-center">
    {% block content %}{% endblock %}
  </div>
</body>

client_interface/templates/client_interface/course_added.html
{% extends 'client_interface/base.html' %}

<head>
    {% block title %}
    <title>
        {{course.title}}
    </title>
    {% endblock %}
</head>

<body>
  {% block content %}
    <div class="px-4 py-5 my-5 text-center">
        <!--TODO: add logo-->
        <img class="d-block mx-auto mb-4" src="#" alt="" width="72" height="57">
        <h1 class="display-5 fw-bold">Курс {{course.title}} успешно создан</h1>
        <div class="col-lg-6 mx-auto">
          <p class="lead mb-4">Любой нужный текст</p>
          <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
            <a href="{% url 'client_interface:process_creation' course.slug %}" class="btn btn-primary btn-lg px-4 gap-3">Перейти к созданию процессов </a>
            <a href="{% url 'client_interface:course_showing' course.slug %}" class="btn btn-secondary btn-lg px-4 gap-3">Перейти на страницу курса </a>
          </div>
        </div>
      </div>
  {% endblock %}
</body>

client_interface/templates/client_interface/course_creation.html
{% extends 'client_interface/base.html' %}
{% load bootstrap5 %}

<head>
    {% block title %}
    <title>
        Создание курса 
    </title>
    {% endblock %}
</head>

<body>
    {% block content %}
    <main class="form-signin w-100 ">
        <h1 class="h3 mb-3 fw-normal">Создать курс</h1>
        <form method="post" enctype="multipart/form-data" class="form-control form-control-sm">
            {% csrf_token %}
            <div class="text-center">
                {{ form.non_field_errors }}
                {{ form.field.errors }}
                <label  for="{{form.title.id_for_label}}">Введите название курса</label>
                <br>
                <br>
                {{form.title}}
            </div>
            <br>
            <div class="text-center">
                {{ form.non_field_errors }}
                {{ form.field.errors }}
                <label for="{{form.description.id_for_label}}">Введите краткое описание курса</label>
                <br>
                <br>
                {{form.description}}
            </div>
            <br>
            <div>
                {{ form.non_field_errors }}
                {{ form.field.errors }}
                <label for="{{form.cover.id_for_label}}">Прикрепите обложку (необязательно)</label>
                <br>
                <br>
                {{form.cover}}
            </div>
            <br>
            <button class="w-100 btn btn-lg btn-primary" style="background-color: #b0b5f8" name='submit' > Создать</button>
        </form>
    </main>
    
    {% endblock %}
</body>

client_interface/templates/client_interface/course_deletion.html
{% extends 'client_interface/base.html' %}

<head>
    {% block title %}
    <title>
        {{course.title}}
    </title>
    {% endblock %}
</head>

<body>
    {% block content %}
    <br>
    <br>
    <div class="text-center">
        <h2> Вы уверены, что хотите удалить курс {{course.title}}?</h2>
        <h6> Все операции, этапы, ключевые моменты и файлы также будут удалены!</h6>
        <form action="{% url 'client_interface:course_deleting' course.slug %}" method="post">
            {% csrf_token %}
          <button class="w-100 btn btn-outline-danger" name='submit' > ДА</button>
        </form>
    </div>
    {% endblock %}
</body>

client_interface/templates/client_interface/course_edit.html
{% extends 'client_interface/base.html' %}
{% load bootstrap5 %}

<head>
    {% block title %}
    <title>
        Редактирование курса
    </title>
    {% endblock %}
</head>

<body>
    {% block content %}
    <main class="form-signin w-100 ">
        <h1 class="h3 mb-3 fw-normal">Изменить курс</h1>
        <form method="post" enctype="multipart/form-data" class="form-control form-control-sm">
            {% csrf_token %}
            <div class="text-center">
                {{ form.non_field_errors }}
                {{ form.field.errors }}
                <label  for="{{form.title.id_for_label}}">Название курса</label>
                <br>
                <br>
                {{form.title}}
            </div>
            <br>
            <div class="text-center">
                {{ form.non_field_errors }}
                {{ form.field.errors }}
                <label for="{{form.description.id_for_label}}">Краткое описание курса</label>
                <br>
                <br>
                {{form.description}}
            </div>
            <br>
            <div>
                {{ form.non_field_errors }}
                {{ form.field.errors }}
                <label for="{{form.cover.id_for_label}}">Прикрепите обложку (необязательно)</label>
                <br>
                <br>
                {{form.cover}}
            </div>
            <br>
            <button class="w-100 btn btn-lg btn-primary" style="background-color: #b0b5f8" name='submit' > Сохранить</button>
        </form>
    </main>
    {% endblock %}
</body>

client_interface/templates/client_interface/process_added.html
{% extends 'client_interface/base.html' %}

<head>
    {% block title %}
    <title>
        {{process.course.title}}
    </title>
    {% endblock %}
</head>

<body>
    {% block content %}
      <div class="px-4 py-5 my-5 text-center">
          <!--TODO: add logo-->
          <img class="d-block mx-auto mb-4" src="#" alt="" width="72" height="57">
          <h1 class="display-5 fw-bold">Процесс {{process.title}} успешно создан</h1>
          <div class="col-lg-6 mx-auto">
            <p class="lead mb-4">Любой нужный текст</p>
            <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
              <a href="{% url 'client_interface:action_creation' process.course.slug  process.slug %}" class="btn btn-primary btn-lg px-4 gap-3">Перейти к созданию этапов </a>
              <a href="{% url 'client_interface:course_showing' process.course.slug %}" class="btn btn-secondary btn-lg px-4 gap-3">Перейти на страницу курса </a>
            </div>
          </div>
        </div>
    {% endblock %}
  </body>

client_interface/templates/client_interface/process_showing.html
{% extends 'client_interface/base.html' %}

<head>
    {% block title %}
    <title>
        {{course.title}}
    </title>
    {% endblock %}
</head>

<body>
    {% block content %}
    <section class="py-5 text-center container-fluid" style="background-color: #525351">
        <div class="px-3 py-5 my-4 text-center">
            {% if process.cover %}
            <img class="d-block mx-auto mb-4" src="{{process.cover.url}}" alt="" width="200" height="200">
            {% endif %}
            <h1 class="display-5 fw-bold">Процесс {{process.title}}</h1>
            <div class="col-lg-6 mx-auto">
              <p class="lead mb-4">{{process.description}}</p>
              <div class="d-grid gap-2 d-sm-flex justify-content-sm-center"></div>
            </div>
          </div>
          <h2> Список операций </h2>
          <br>
        <div class="row py-lg-0">
          <div class="album py-0 bg-light">
            <div class="container-fluid">
              <div class="row row-cols-md-3 row-cols-sm-2 row-cols-md-3 g-2">
                {% for action in actions %}
                <div class="col-md-3">
                    <div class="card shadow-sm">
                      <div class="card-body">
                        <a class="card-link" href="{% url 'client_interface:action_showing' process.course.slug process.slug action.slug %}"> {{action.title}} </a>
                        <a class="btn btn-outline-primary" href="{% url 'client_interface:action_editing' process.course.slug process.slug action.slug %}"> Редактировать этап</a>
                        <a class="btn btn-outline-primary" href="{% url 'client_interface:action_deleting' process.course.slug process.slug action.slug %}">Удалить этап</a>
                      </div>
                    </div>
                  </div>
                  {% empty %}
                  <div class="col-sm-3 col-sm-6 mx-auto">
                    <h1 class="fw-light">Операции скоро будут добавлены</h1>
                  </div>
                  {% endfor %}
              </div>
              <div class="text-center">
                <a class="btn btn-outline-primary" href="{% url 'client_interface:action_creation' process.course.slug process.slug %}">Добавить новую операцию </a>
              </div> 
            </div>
        </div> 
    </section>
  {% endblock %}   
</body>

client_interface/templates/client_interface/step_added.html
{% extends 'client_interface/base.html' %}


<head>
  {%block title %}
  <title>
    Курс {{step.action.process.course.title}}
  </title>
  {% endblock %}
</head>

<body>
    {% block content %}
    <div class="px-4 py-5 my-5 text-center">
        <h1 class="display-5 fw-bold">Ключевой момент {{step.title}} для этапа {{step.action.title}} успешно создан</h1>
        <div class="col-lg-6 mx-auto">
          <p class="lead mb-4">Любой нужный текст</p>
          <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
            <a href="{% url 'client_interface:step_creation' step.action.process.course.slug step.action.process.slug %}" class="btn btn-secondary btn-lg px-4 gap-3">Создать еще один ключевой момент</a>
            <a href="{% url 'client_interface:action_creation' step.action.process.slug step.action.process.course.slug %}" class="btn btn-secondary btn-lg px-4 gap-3">Вернуться к созданию этапов</a>
            <a href="{% url 'client_interface:action_showing' process.course.slug process.slug step.action.slug %}" class="btn btn-secondary btn-lg px-4 gap-3">Перейти на страницу этапа </a>
            <a href="#" class="btn btn-primary btn-lg px-4 gap-3">Загрузить курс в бота</a>
            </div>
        </div>
      </div>
    {% endblock %}
</body>

client_interface/templates/client_interface/step_deletion.html
{% extends 'client_interface/base.html' %}

<head>
    {% block title %}
    <title>
        {{step.title}}
    </title>
    {% endblock %}
</head>

<body>
    {% block content %}
    <br>
    <br>
    <div class="text-center">
        <h2> Вы уверены, что хотите удалить ключевой момент {{step.title}}?</h2>
        <form action="{% url 'client_interface:step_deleting' course.slug process.slug action.slug step.slug %}" method="post">
            {% csrf_token %}
          <button class="w-100 btn btn-outline-danger" name='submit' > ДА</button>
        </form>
    </div>
    {% endblock %}
</body>